name: CI-CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: asia-south2
  GAR_REPO_NAME: cypher-repo

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Build and Push Backend Image
      run: |-
        docker build -t ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPO_NAME }}/cypher-backend:${{ github.sha }} -f Dockerfile.backend .
        docker push ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPO_NAME }}/cypher-backend:${{ github.sha }}

    - name: Build and Push Frontend Image
      run: |-
        docker build -t ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPO_NAME }}/cypher-frontend:${{ github.sha }} -f Dockerfile.frontend .
        docker push ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPO_NAME }}/cypher-frontend:${{ github.sha }}

  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Configure Docker
      run: gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev

    - name: Deploy Backend to Cloud Run
      id: deploy_backend
      run: |-
        gcloud run deploy cypher-backend \
          --image=${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPO_NAME }}/cypher-backend:${{ github.sha }} \
          --region=${{ env.GCP_REGION }} \
          --platform=managed \
          --allow-unauthenticated \
          --set-env-vars="GROQ_API_KEY=${{ secrets.GROQ_API_KEY }},VIRUSTOTAL_API_KEY=${{ secrets.VIRUSTOTAL_API_KEY }}"

    - name: Get Backend URL
      id: get_backend_url
      run: echo "backend_url=$(gcloud run services describe cypher-backend --platform managed --region ${{ env.GCP_REGION }} --format 'value(status.url)')" >> $GITHUB_OUTPUT

    - name: Deploy Frontend to Cloud Run
      run: |-
        gcloud run deploy cypher-frontend \
          --image=${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPO_NAME }}/cypher-frontend:${{ github.sha }} \
          --region=${{ env.GCP_REGION }} \
          --platform=managed \
          --allow-unauthenticated \
          --set-env-vars="NEXT_PUBLIC_BACKEND_URL=${{ steps.get_backend_url.outputs.backend_url }}"
